blog/apps/contacto/urls.py
from django.urls import path 
from . import views

app_name = 'apps.contacto'

urlpatterns = [
    path('contacto/', views.ContactoUsuario.as_view(), name = 'contacto'),
]

blog/apps/posts/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    # path('posts/', posts, name='posts'), #En vista por funcion
    path('', views.PostListView.as_view(), name='posts'),
    path('posts/<int:id>/', views.PostDetailView.as_view(), name='post_individual'),
    path('post/categoria', views.CategoriaCreateView.as_view(), name='crear_categoria'),
    path('addPost', views.AddPost, name='addpost'),
    path('posts/<int:pk>/edit/', views.EditarPost, name='editarPost'),
    path('posts/<int:pk>/eliminar/', views.EliminarPost, name='borrarPost'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/add/<int:articulo_id>/', views.add_comment, name='add_comment'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
    path('categoria/<int:pk>/posts/', views.PostsPorCategoriaView.as_view(), name='posts_por_categoria'),
    path('categorias/',views.CategoriasListView.as_view(), name='categorias'),
    path('<int:pk>/like', views.like_post, name='like'),
    path('categorias/<int:pk>/eliminar/', views.CategoriaDeleteView.as_view(), name='borrar_categoria'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index
from .views import nosotros
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('nosotros/', nosotros, name='nosotros'),
    # path('', include('apps.posts.urls')),
    path('', include('apps.contacto.urls')),
    path('', include('apps.usuarios.urls')),
    path('posts/', include('apps.posts.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += staticfiles_urlpatterns() 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/apps/contacto/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Contacto(models.Model):
    nombre_apellido = models.CharField(max_length=150)
    email = models.EmailField()
    asunto = models.CharField(max_length=50)
    mensaje = models.TextField()
    fecha = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.nombre_apellido

blog/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    foto = models.ImageField(upload_to='usuarios', null=True)


    

blog/apps/contacto/forms.py
from django import forms
from .models import Contacto

# Register your models here.
class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombre_apellido','email','asunto','mensaje']
    

blog/apps/posts/forms.py
from django import forms
from .models import Post, Comment, Categoria

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class CrearPostFrom(forms.ModelForm):
   class Meta:
       model = Post
       fields = '__all__'

class NuevaCategoriaForm(forms.ModelForm):
    class Meta:
       model = Categoria
       fields = '__all__'



class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ['titulo', 'subtitulo', 'texto', 'imagen', 'categoria']

class CommentForm(forms.ModelForm):
    text = forms.CharField(label='Escribe tu comentario', widget=forms.Textarea(attrs={
        "rows": 2,
        "class": "form-control",
        "placeholder": "Escribe tu comentario aquí...",
        "name": "text"
    }))
    class Meta:
        model = Comment
        fields = ['text']
        
    

blog/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django.contrib.auth import authenticate, login


class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

blog/apps/contacto/views.py
from .forms import ContactoForm
from django.contrib import messages
from django.views.generic import CreateView
from django.urls import reverse_lazy

# Create your views here.

class ContactoUsuario(CreateView):
    template_name = 'contacto/contacto.html'
    form_class = ContactoForm
    success_url = reverse_lazy('apps.contacto:contacto')
      
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['request'] = self.request
        return context
    
    def form_valid(self,form):
        messages.success(self.request, 'Consulta enviada.')
        return super().form_valid(form)

blog/apps/posts/views.py
from typing import Any, Dict, Optional
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment, Categoria
from .forms import PostForm, CommentForm
from django.views.generic import ListView, DetailView, DeleteView, UpdateView
from django.contrib import messages
from django.views.generic import CreateView
from .forms import ComentarioForm, CrearPostFrom, NuevaCategoriaForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required


class PostListView(ListView):
    model = Post
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'

    def get_queryset(self):
          queryset = super().get_queryset()
          categoria_id = self.request.GET.get('categoria_id')
          if categoria_id and categoria_id.isnumeric():
              queryset = queryset.filter(categoria__id = categoria_id)
          
          orden = self.request.GET.get('orden')
          if orden == 'reciente':
               queryset = queryset.order_by('-fecha')
          elif orden == 'antiguo':
               queryset = queryset.order_by('fecha')
          elif orden == 'alfabetico':
               queryset = queryset.order_by('titulo')
          return queryset
     
    def get_context_data(self, **kwargs):
          context = super().get_context_data(**kwargs)
          context['orden'] = self.request.GET.get('orden', 'reciente')
          categoria_id = self.request.GET.get('categoria_id')
          if categoria_id and categoria_id.isnumeric():
              context['categoria'] = Categoria.objects.get(pk=self.request.GET.get('categoria_id'))
          return context


class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_individual.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'
    queryset = Post.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context

   
def EliminarPost(request, pk):
    if not request.user.is_staff:
        messages.error(request, 'No tienes permiso para estar aquí')
        return redirect('index')
    
    post = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        post.delete()
        messages.success(request, "Articulo eliminado")
        return redirect('posts:posts')
    return render(request, 'posts/confirmarBorrar.html', {"articulo": post})

@login_required
def AddPost(request):
    if not request.user.is_staff:
        messages.error(request, 'No tienes permiso para estar aquí')
        return redirect('index')
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES) ##REQUEST FILE PARA LAS IMAGENES
        if form.is_valid():
            post = form.save(commit=False)
            post.autor = request.user
            # articulo.author = request.user #autor del articulo            
            post.save()
            return redirect('posts:posts')
    else:
        form = PostForm()
    
    return render(request, 'posts/addPost.html', {'form': form})



def EditarPost(request, pk):
    if not request.user.is_staff:
        messages.error(request, 'No tienes permiso para estar aquí')
        return redirect('index')
     
    posts = get_object_or_404(Post, pk=pk)

    # Solo el autor puede editar la noticia
    # if articulo.author != request.user:
    #     return HttpResponseForbidden("No tienes permisos para editar este artículo.")

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=posts)
        if form.is_valid():
            form.save()
            return redirect('posts:post_individual', id=pk)
    else:
        form = PostForm(instance=posts)

    context = {
        'form': form,
    }
    return render(request, 'posts/editarPost.html', context)


def add_comment(request, articulo_id):
    post = get_object_or_404(Post, id=articulo_id)
    if request.method == 'POST':
        text = request.POST.get('text')
        author = request.user
        # creacion de comentario
        Comment.objects.create(articulo=post, author=author, text=text)
    return redirect('posts:post_individual', id=articulo_id)


def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    if request.method == "POST":
        if comment.author == request.user or request.user.is_staff:
            comment.delete()
        else:
            messages.error(request, 'No tienes permiso')
        return redirect('posts:post_individual', id=comment.articulo.pk)

    # Confirmacion
    ctx = {
        "comentario": comment
    }
    return render(request, 'posts/comentarios/confirmar_eliminar.html', ctx)

def edit_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    #mensaje de error si no sos el autor
    if comment.author != request.user:
        messages.error(request, 'Usuario sin permisos para editar este comentario.')
        return redirect('posts:post_individual', id=comment.articulo.pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('posts:post_individual', id=comment.articulo.pk)
    else:
        form = CommentForm(instance=comment)

    context = {
        'form': form,
        'comment': comment,
    }
    return render(request, 'posts/comentarios/editComentario.html', context)


class CategoriaCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Categoria
    form_class = NuevaCategoriaForm

    def get_success_url(self):
        messages.success(self.request, '¡categoria creada con exito!')
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            return reverse_lazy('posts:categorias')
    
    def test_func(self):
        return self.request.user.is_staff
        
class PostsPorCategoriaView(ListView):
     model = Post
     template_name = 'posts/posts_por_categoria.html'
     context_object_name = 'posts'

     def get_queryset(self):
          return Post.objects.filter(categoria_id=self.kwargs['pk'])
     

class CategoriasListView(ListView):
    model = Post
    template_name = 'posts/lista_categorias.html'
    context_object_name = 'posts'


@login_required
def like_post(request, pk):
    if request.method == "POST":
        post = Post.objects.get(pk=pk)
        if request.user in post.likes.all():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)
    return redirect('posts:post_individual', pk)




class CategoriaDeleteView(DeleteView):
    model = Categoria
    template_name = 'posts/categoria_confirm_delete.html'
    success_url = reverse_lazy('posts:categorias')

blog/apps/usuarios/views.py
from typing import Any, Dict, Set
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models.query import QuerySet
from django.views.generic import CreateView, TemplateView, ListView, DeleteView
from .forms import RegistroForm, Usuario
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.posts.models import Post,Comment
 


class Login(LoginView):
    template_name = "usuarios/login.html"

    def get_success_url(self) -> str:
        messages.success(self.request, 'Inicio de sesión exitoso!')
        return super().get_success_url()

class Registro(CreateView):
    form_class = RegistroForm
    success_url = reverse_lazy('apps.usuario:login')
    template_name = 'usuarios/registro.html'

    def get_success_url(self) -> str:
        messages.success(self.request, 'Registro exitoso!')
        print(super().get_success_url())
        return super().get_success_url()

class Logout(LogoutView):
    success_url = reverse_lazy("index")

    def get_success_url(self):
        messages.success(self.request, 'Cierre de sesión exitoso!')
        
        success_url = self.success_url
        next_page = self.request.GET.get("next", "")
        if next_page:
            success_url = next_page
        return success_url
        
       

    

class ConfirmLogout(TemplateView):
    template_name = 'usuarios/confirm_logout.html'
    
    def get_context_data(self):
        next_page = self.request.GET.get("next", "")
        if not next_page:
            next_page = reverse('index')
        return {"next": next_page}
    

class UsuariolistView(LoginRequiredMixin, ListView):
    model = Usuario
    context_object_name = 'usuarios'

    def get_queryset(self):
        queriset = super().get_queryset()
        print(queriset)
        queriset = queriset.exclude(is_superuser=True)
        return queriset
    
class UsuarioDeleteview(LoginRequiredMixin, DeleteView):
    model = Usuario
    template_name = 'usuario/eliminar_usuario.html'
    success_url = reverse_lazy('apps.usuario:usuario_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        colaborador_group = Group.objects.get(name='colaborador')
        es_colaborador = colaborador_group in self.object.groups.all()
        context['es_colaborador'] = es_colaborador
        return context

    def post(self, request, *args, **kwargs):
        eliminar_comentarios = request.POST.get('eliminar_comentarios', False)
        eliminar_posts = request.POST.get('eliminar_posts', False)
        self.object = self.get_object()
        if eliminar_comentarios:
            Comment.objects.filter(usuario=self.object).delete()
        
        if eliminar_posts:
            Post.objects.filter(autor=self.object).delete()
            messages.success(request, f'Usuario {self.objact.username} eliminado correctamente')
        return self.delete(request, *args, **kwargs)

blog/blog/views.py
from django.shortcuts import render


def index(request):
        return render(request, 'index.html')

def nosotros(request):
    return render(request, 'nosotros.html')

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="es-ar">

<head>
    
    <title>{% block title %}ECO FRIENDLY{% endblock title%}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"type="image/x-icon">

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    
    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&amp;display=swap" rel="stylesheet"> 
        
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        
    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}" rel="stylesheet">
        
    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/default.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/sceditor@3/minified/sceditor.min.js"></script>
</head>

<body>
    <header>
        <div class="container-fluid bg-light pt-3 d-none d-lg-block">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                        <div class="d-inline-flex align-items-center">
                            <p><i class="fa fa-envelope mr-2"></i>ecofriendly@gmail.com</p>
                            <p class="text-body px-3">|</p>
                            <p><i class="fa fa-phone-alt mr-2"></i>+54 3644 678999</p>
                        </div>
                    </div>
                    <div class="col-lg-6 text-center text-lg-right">
                        <div class="d-inline-flex align-items-center">
                            <a class="text-primary px-3" href="">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a class="text-primary px-3" href="">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a class="text-primary px-3" href="">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="container-fluid position-relative nav-bar p-0">
            <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
                <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-3 py-lg-0 pl-3 pl-lg-5">
                    <a href="" class="navbar-brand">
                        <h1 class="m-0 text-primary"><span class="text-dark">Eco </span>Friendly</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
                        <div class="navbar-nav ml-auto py-0">
                            <a href="{% url 'index' %}" class="nav-item nav-link active">Inicio</a>
                            <a href="{% url 'nosotros' %}" class="nav-item nav-link">Nosotros</a>
                            <a href="{% url 'posts:posts' %}" class="nav-item nav-link">Artículos</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">Categorías</a>
                                <div class="dropdown-menu border-0 rounded-0 m-0">
                                    <a href="{% url 'posts:categorias' %}" class="dropdown-item">Todas las categorías</a>
                                    <hr>
                                    {% for categoria in categorias %}
                                    <a href="{{categoria.get_filterby_url}}" class="dropdown-item">{{categoria.nombre}}</a>
                                    {% endfor %}
                                    
                                </div>
                            </div>
                            <a href="{% url 'apps.contacto:contacto' %}" class="nav-item nav-link">Contacto</a>
                        </div>
                                <div class="nav-item dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        Ingresar
                                    </a>
                                    {% load path_tags %}
                                    <div class="dropdown-menu border-0 rounded-0 m-0">
                                        {% if user.is_authenticated %}
                                        <a href="#" class="dropdown-item">Perfil</a>
                                        {% if user.is_staff %}
                                        <a href="{% url 'posts:addpost' %}" class="dropdown-item">Publicar</a>
                                        {% endif %}
                                        <a href="{% confirm_logout_path %}" class="dropdown-item">Cerrar sesión</a>
                                        {% else %}
                                        <a href="{% register_path %}" class="dropdown-item">Registrarse</a>
                                        <a href="{% login_path %}" class="dropdown-item">Iniciar sesión</a>
                                        {% endif %}
                                    </div>
                            
                    </div>
                </nav>
            </div>
        </nav>
    </header>

    <main>
        
        {% block contenido %}

        {% endblock %}

    </main>

    <footer>
        <div class="container-fluid bg-dark text-white-50 py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
            <div class="row pt-5">
                <div class="col-lg-5 col-md-6 mb-5"> 
                    <a href="" class="navbar-brand">
                        <h1 class="text-primary"><span class="text-white">Eco </span>Friendly</h1>
                    </a>
                    <p>¡La actualidad medioambiental <br> al alcance de un click!</p>
                    <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Seguinos:</h6>
                    <div class="d-flex justify-content-start">
                        <a class="btn btn-outline-primary btn-square mr-2" href="#"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-primary btn-square mr-2" href="#"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-primary btn-square" href="#"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 mb-5">
                    <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Contenido</h5>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-white-50 mb-2" href="{% url 'index' %}"><i class="fa fa-angle-right mr-2"></i>Inicio</a>
                        <a class="text-white-50 mb-2" href="{% url 'nosotros' %}"><i class="fa fa-angle-right mr-2"></i>Nosotros</a>
                        <a class="text-white-50 mb-2" href="{% url 'posts:posts' %}"><i class="fa fa-angle-right mr-2"></i>Artículos</a>
                        <a class="text-white-50 mb-2" href="{% url 'posts:categorias' %}" ><i class="fa fa-angle-right mr-2"></i>Categorías</a>
                        <a class="text-white-50 mb-2" href="{% url 'apps.contacto:contacto' %}"><i class="fa fa-angle-right mr-2"></i>Contacto</a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 mb-5">
                    <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Contactanos:</h5>
                    <p><i class="fa fa-map-marker-alt mr-2"></i>Mitre 123, Resistencia, Chaco Argentina</p>
                    <p><i class="fa fa-phone-alt mr-2"></i>+054 3644 678999</p>
                    <p><i class="fa fa-envelope mr-2"></i>ecofriendly@gmail.com</p>
                    <!-- <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Newsletter</h6> -->
                    <!-- <div class="w-100">
                        <div class="input-group">
                            <input type="text" class="form-control border-light" style="padding: 25px;" placeholder="Your Email">
                            <div class="input-group-append">
                                <button class="btn btn-primary px-3">Sign Up</button>
                            </div>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
        <div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
            <div class="row">
                <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
                    <p class="m-0 text-white-50">Copyright © <a href="#">EcoFriendly</a>. Todos los derechos reservados.
                    </p>
                </div>
                <div class="col-lg-6 text-center text-md-right">
                    <p class="m-0 text-white-50">Diseñado por <a href="#">Grupo 18 INFORMATORIO</a>
                    </p>
                </div>
            </div>
        </div>
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top" style="display: inline;"><i class="fa fa-angle-double-up"></i></a>
    </footer>

    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
        </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
        integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
        </script>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js'%}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static 'mail/jqBootstrapValidation.min.js' %}"></script>
    <script src="{% static 'mail/contact.js' %}"></script>
  
    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

blog/templates/carousel.html
<section class="container">
    {% load static %}
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'img/carrousel0.jpg' %}" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/carrousel1.jpg' %}" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'img/carrousel2.jpg' %}" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
</section>